#!/usr/bin/env python3
# steer-runtime: version=0.1.1 components=context,proc,learn
# Generated by steer; DO NOT EDIT. Regenerate: steer bundle --with context,proc,learn
#
# This is the skill's bundled steer runtime, amalgamated from the steer
# package (https://github.com/bh-rat/steer, MIT) so the skill runs
# without steer installed. SKILL.md calls it (python3 scripts/steer.py
# <command>) and sibling scripts can import it (from steer import ...).
# Python 3.11+, stdlib only. State lives under ~/.steer and
# <workspace>/.steer, same as the installed CLI.
"""Bundled steer runtime for this skill (generated; do not edit)."""

import argparse
import json
import json as json_module
import os
import platform
import re
import shlex
import shutil
import signal
import socket
import sqlite3
import subprocess
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Callable, Dict, Iterable, List, Optional, Tuple, Union

__version__ = "0.1.1"
STEER_RUNTIME_COMPONENTS = ('context', 'proc', 'learn',)

# ===== steer/paths.py =====

"""
Path conventions for steer.

Steer keeps all of its own data under a single home directory
(``~/.steer`` by default, overridable with ``STEER_HOME``). Each skill
gets a private data directory for its store and file-backed secrets.

Workspace-scoped data (flow state, workspace stores) lives under
``<workspace>/.steer/`` so it travels with the project being operated on.
"""


STEER_HOME_ENV = "STEER_HOME"
SKILL_ENV = "STEER_SKILL"
SKILL_FILE = "SKILL.md"

# The open spec's name rule (also what makes a name a safe directory name).
SKILL_NAME_RE = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*$")
SKILL_NAME_MAX = 64

# Flow/process names: looser than skill names, but still a single safe
# path component (no separators, no dot-files, no traversal).
_COMPONENT_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$")


def checked_skill_name(name: str) -> str:
    """Validate a skill name before it becomes a filesystem path.

    Skill names turn into directories under ~/.steer and
    <workspace>/.steer, and the name can come from a third-party
    SKILL.md's frontmatter. Enforcing the spec's kebab-case rule here
    stops a hostile `name: ../../x` from escaping steer's data dirs.
    """
    if (not name or not isinstance(name, str)
            or len(name) > SKILL_NAME_MAX or not SKILL_NAME_RE.match(name)):
        raise ValueError(
            f"Invalid skill name {name!r}: must be lowercase kebab-case "
            f"(letters, digits, single hyphens; max {SKILL_NAME_MAX} chars). "
            f"Fix the 'name' in SKILL.md, or pass --skill <valid-name>."
        )
    return name


def checked_path_component(name: str, what: str) -> str:
    """Validate a user-supplied name used as a single path component."""
    if not name or not isinstance(name, str) or not _COMPONENT_RE.match(name):
        raise ValueError(
            f"Invalid {what} name {name!r}: use letters, digits, dots, "
            f"hyphens, or underscores (must not start with a dot; max 64 "
            f"chars)."
        )
    return name


def steer_home() -> Path:
    """Steer's own data directory (~/.steer or $STEER_HOME)."""
    override = os.environ.get(STEER_HOME_ENV)
    if override:
        return Path(override).expanduser()
    return Path.home() / ".steer"


def skill_data_dir(skill_name: str, create: bool = False) -> Path:
    """Private data directory for a skill (store.db, secrets.json)."""
    path = steer_home() / "skills" / checked_skill_name(skill_name)
    if create:
        path.mkdir(parents=True, exist_ok=True, mode=0o700)
    return path


def workspace_steer_dir(workspace: str = ".", create: bool = False) -> Path:
    """Workspace-scoped steer directory (<workspace>/.steer)."""
    path = Path(workspace).expanduser().resolve() / ".steer"
    if create:
        path.mkdir(parents=True, exist_ok=True)
    return path


def find_skill_root(start: str = ".") -> Optional[Path]:
    """Walk upward from `start` looking for a directory containing SKILL.md.

    Lets `steer` CLI commands infer which skill they're operating on when
    run from inside a skill directory.
    """
    current = Path(start).expanduser().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / SKILL_FILE).is_file():
            return candidate
    return None


def infer_skill_name(explicit: Optional[str] = None, start: str = ".") -> Optional[str]:
    """Resolve the skill name a command should operate on.

    Resolution order: explicit --skill flag, STEER_SKILL env var,
    nearest SKILL.md frontmatter name (falling back to its directory name).
    """
    if explicit:
        return explicit
    env_name = os.environ.get(SKILL_ENV)
    if env_name:
        return env_name
    root = find_skill_root(start)
    if root is not None:
        pass

        skill = Skill.load(root)
        if skill.name:
            return skill.name
        return root.name
    return None


def skill_search_roots(project_dir: str = ".") -> List[Path]:
    """Directories that agent products scan for installed skills.

    Covers the cross-client ``.agents/skills`` convention from the open
    Agent Skills standard plus the Claude Code native locations, at both
    project and user scope. Project paths come first (project overrides
    user on name collisions, per the spec's client guidance).
    """
    project = Path(project_dir).expanduser().resolve()
    return [
        project / ".claude" / "skills",
        project / ".agents" / "skills",
        Path.home() / ".claude" / "skills",
        Path.home() / ".agents" / "skills",
    ]

# ===== steer/output.py =====

"""
Output utilities: JSON printing and the skill-script result envelope.

Usage:
    from steer.output import print_envelope

    print_envelope("ok", "Report generated",
                   data={"rows": 120}, artifacts=["out/report.pdf"])
"""


# How agent-facing hints spell a steer command. "steer" for the installed
# CLI; a skill's bundled runtime (see vendor.py) rebinds it to
# "python3 scripts/steer.py" so hints match how the agent invokes it.
CLI_HINT = "steer"


def output_json(data, file=None):
    """Write data as formatted JSON.

    Args:
        data: Any JSON-serializable data.
        file: Output file (default: stdout, resolved at call time so
            redirection works).
    """
    print(json_module.dumps(data, indent=2), file=file or sys.stdout)


# Recommended envelope statuses. `status` is a free string; these cover
# the cases agents need to branch on.
STATUS_OK = "ok"
STATUS_ERROR = "error"
STATUS_BLOCKED = "blocked"
STATUS_NEEDS_INPUT = "needs_input"
STATUS_PARTIAL = "partial"


def envelope(status, summary, data=None, artifacts=None, errors=None):
    """Build the standard result envelope for skill scripts.

    Every script in every skill invents its own JSON shape for "here's
    what happened". This is one canonical shape:

        {"status": "ok", "summary": "...", "data": {...},
         "artifacts": ["out/report.pdf"], "errors": [...]}

    Args:
        status: One of the STATUS_* constants (or any short string).
        summary: One human-readable sentence about the outcome.
        data: Optional machine-readable payload.
        artifacts: Optional list of file paths this run produced.
        errors: Optional list of error strings.
    """
    result = {"status": status, "summary": summary}
    if data is not None:
        result["data"] = data
    if artifacts:
        result["artifacts"] = [str(a) for a in artifacts]
    if errors:
        result["errors"] = list(errors)
    return result


def print_envelope(status, summary, data=None, artifacts=None, errors=None,
                   file=None):
    """Print a result envelope as JSON to stdout (agents parse this).

    Returns a sensible process exit code: 0 unless status is "error".
    """
    result = envelope(status, summary, data=data, artifacts=artifacts,
                      errors=errors)
    print(json_module.dumps(result, indent=2), file=file or sys.stdout)
    return 0 if status != STATUS_ERROR else 1

# ===== steer/frontmatter.py =====

"""
SKILL.md frontmatter parsing and emission.

Implements the YAML subset that appears in real skill frontmatter
(scalars, quoted strings, inline and block lists, one level of nested
maps such as ``metadata``, and block scalars ``|`` and ``>``) without a
YAML dependency. Steer stays zero-dependency on purpose.

The parser is deliberately lenient where the spec's client guidance is
lenient (unquoted colons in descriptions are a common authoring
mistake), and reports structural problems instead of raising.
"""


DELIMITER = "---"


def split_document(content: str) -> Tuple[Optional[str], str]:
    """Split a SKILL.md document into (frontmatter_text, body).

    Returns (None, content) when no frontmatter block is present.
    """
    content = content.lstrip("﻿")  # editors add BOMs invisibly
    lines = content.splitlines(keepends=True)
    if not lines or lines[0].strip() != DELIMITER:
        return None, content
    for i in range(1, len(lines)):
        if lines[i].strip() == DELIMITER:
            return "".join(lines[1:i]), "".join(lines[i + 1:])
    return None, content  # Unterminated block: treat the whole file as body


def _parse_scalar(raw: str) -> Any:
    """Parse a scalar value: quoted strings, booleans, inline lists."""
    value = raw.strip()
    if not value:
        return ""
    if value.startswith("[") and value.endswith("]"):
        inner = value[1:-1].strip()
        if not inner:
            return []
        return [_parse_scalar(part) for part in _split_inline_list(inner)]
    if value.startswith('"') and value.endswith('"') and len(value) >= 2:
        return _unescape_double_quoted(value[1:-1])
    if value.startswith("'") and value.endswith("'") and len(value) >= 2:
        return value[1:-1].replace("''", "'")
    if value in ("true", "True"):
        return True
    if value in ("false", "False"):
        return False
    if re.fullmatch(r"-?\d+", value):
        return int(value)
    return value


_DQ_ESCAPES = {"\\": "\\", '"': '"', "n": "\n", "t": "\t"}


def _unescape_double_quoted(text: str) -> str:
    """Undo the escapes a YAML double-quoted scalar can carry (the subset
    emit() writes plus \\n/\\t); unknown escapes pass through literally."""
    out: List[str] = []
    i = 0
    while i < len(text):
        ch = text[i]
        if ch == "\\" and i + 1 < len(text):
            mapped = _DQ_ESCAPES.get(text[i + 1])
            if mapped is not None:
                out.append(mapped)
                i += 2
                continue
        out.append(ch)
        i += 1
    return "".join(out)


def _split_inline_list(inner: str) -> List[str]:
    """Split 'a, b, "c, d"' on commas outside quotes."""
    parts = []
    current = []
    quote = None
    for ch in inner:
        if quote:
            current.append(ch)
            if ch == quote:
                quote = None
        elif ch in "\"'":
            quote = ch
            current.append(ch)
        elif ch == ",":
            parts.append("".join(current).strip())
            current = []
        else:
            current.append(ch)
    if current:
        parts.append("".join(current).strip())
    return [p for p in parts if p]


def _indent_of(line: str) -> int:
    return len(line) - len(line.lstrip(" "))


def parse(text: str) -> Tuple[Dict[str, Any], List[str]]:
    """Parse frontmatter text into a dict.

    Handles arbitrarily nested maps and lists (including lists of maps,
    as used by Claude Code's `hooks` frontmatter). Returns (data,
    problems); problems describe lines the parser could not make sense
    of, and parsing continues past them.
    """
    problems: List[str] = []
    lines = text.splitlines()
    data, _ = _parse_map(lines, 0, 0, problems)
    return data, problems


def _read_block_scalar(lines: List[str], start: int, style: str,
                       parent_indent: int = 0) -> Tuple[str, int]:
    """Read a ``|`` or ``>`` block scalar starting at `start`.

    Content belongs to the block while it is indented deeper than the
    key that opened it (`parent_indent`); a sibling or dedented key ends
    the block.
    """
    collected = []
    i = start
    while i < len(lines):
        line = lines[i]
        if line.strip() and _indent_of(line) <= parent_indent:
            break
        collected.append(line)
        i += 1
    # Strip the common indentation
    indents = [_indent_of(ln) for ln in collected if ln.strip()]
    base = min(indents) if indents else 0
    body_lines = [ln[base:] if len(ln) >= base else "" for ln in collected]
    while body_lines and not body_lines[-1].strip():
        body_lines.pop()
    if style.startswith("|"):
        text = "\n".join(body_lines)
    else:  # folded: newlines become spaces, blank lines become newlines
        paragraphs: List[str] = []
        current: List[str] = []
        for ln in body_lines:
            if ln.strip():
                current.append(ln.strip())
            elif current:
                paragraphs.append(" ".join(current))
                current = []
        if current:
            paragraphs.append(" ".join(current))
        text = "\n".join(paragraphs)
    if not style.endswith("-"):
        text += "\n" if text else ""
    return text, i


def _skip_blank(lines: List[str], i: int) -> int:
    while i < len(lines) and (not lines[i].strip()
                              or lines[i].strip().startswith("#")):
        i += 1
    return i


def _parse_map(lines: List[str], i: int, indent: int,
               problems: List[str]) -> Tuple[Dict[str, Any], int]:
    """Parse `key: value` entries at exactly `indent` until dedent."""
    mapping: Dict[str, Any] = {}
    while True:
        i = _skip_blank(lines, i)
        if i >= len(lines) or _indent_of(lines[i]) < indent:
            return mapping, i
        line = lines[i]
        if _indent_of(line) > indent:
            problems.append(
                f"line {i + 1}: unexpected indentation: {line.strip()!r}")
            i += 1
            continue
        stripped = line.strip()
        if stripped.startswith("- "):
            return mapping, i  # caller decides; a list at map level is odd
        if ":" not in stripped:
            problems.append(
                f"line {i + 1}: expected 'key: value': {stripped!r}")
            i += 1
            continue
        key, _, rest = stripped.partition(":")
        key = key.strip()
        rest = rest.strip()
        if rest.startswith("|") or rest.startswith(">"):
            mapping[key], i = _read_block_scalar(lines, i + 1, style=rest,
                                                 parent_indent=indent)
            continue
        if rest:
            mapping[key] = _parse_scalar(rest)
            i += 1
            continue
        mapping[key], i = _parse_value_block(lines, i + 1, indent, problems)
    return mapping, i


def _parse_value_block(lines: List[str], i: int, parent_indent: int,
                       problems: List[str]) -> Tuple[Any, int]:
    """Parse what follows a `key:` with no inline value: a deeper-indented
    list or map, or nothing (empty string)."""
    i = _skip_blank(lines, i)
    if i >= len(lines) or _indent_of(lines[i]) <= parent_indent:
        return "", i
    child_indent = _indent_of(lines[i])
    if lines[i].lstrip().startswith("- "):
        return _parse_list(lines, i, child_indent, problems)
    return _parse_map(lines, i, child_indent, problems)


def _parse_list(lines: List[str], i: int, indent: int,
                problems: List[str]) -> Tuple[List[Any], int]:
    """Parse `- item` entries at exactly `indent` until dedent.

    A list item may be a scalar, or open a map (`- key: value` with
    continuation lines indented past the dash), or open a nested block.
    """
    items: List[Any] = []
    while True:
        i = _skip_blank(lines, i)
        if i >= len(lines) or _indent_of(lines[i]) < indent:
            return items, i
        line = lines[i]
        if _indent_of(line) > indent or not line.strip().startswith("-"):
            problems.append(
                f"line {i + 1}: expected list item: {line.strip()!r}")
            i += 1
            continue
        content = line.strip()[1:].lstrip()  # text after the dash
        item_indent = indent + 2             # canonical continuation indent
        if not content:
            value, i = _parse_value_block(lines, i + 1, indent, problems)
            items.append(value)
            continue
        if ":" in content and not content.startswith(("'", '"', "[")):
            # `- key: value` opens a map item; rewrite the dash as spaces so
            # the map parser sees a normally indented first entry.
            rewritten = lines[:i] + [" " * item_indent + content] + lines[i + 1:]
            value, i = _parse_map(rewritten, i, item_indent, problems)
            items.append(value)
            continue
        items.append(_parse_scalar(content))
        i += 1
    return items, i


_NEEDS_QUOTING = re.compile(r'(^[\s\-?:,\[\]{}#&*!|>\'"%@`])|(:\s)|(\s#)|(\s$)|(^$)')


def _emit_scalar(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    text = str(value)
    if _NEEDS_QUOTING.search(text) or text in ("true", "false", "null"):
        escaped = text.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    return text


def _emit_value(key: str, value: Any, indent: int, lines: List[str]) -> None:
    pad = " " * indent
    if isinstance(value, dict):
        if not value:
            return
        lines.append(f"{pad}{key}:")
        for k, v in value.items():
            _emit_value(k, v, indent + 2, lines)
    elif isinstance(value, list):
        if not value:
            return
        lines.append(f"{pad}{key}:")
        item_pad = " " * (indent + 2)
        for item in value:
            if isinstance(item, dict) and item:
                # Emit every key at the continuation indent, then fold the
                # first line onto the dash: `- key: ...`
                sub: List[str] = []
                for k, v in item.items():
                    _emit_value(k, v, indent + 4, sub)
                sub[0] = f"{item_pad}- {sub[0].lstrip()}"
                lines.extend(sub)
            else:
                lines.append(f"{item_pad}- {_emit_scalar(item)}")
    elif isinstance(value, str) and "\n" in value:
        lines.append(f"{pad}{key}: |")
        for part in value.rstrip("\n").split("\n"):
            lines.append(f"{pad}  {part}")
    else:
        lines.append(f"{pad}{key}: {_emit_scalar(value)}")


def emit(data: Dict[str, Any]) -> str:
    """Emit a frontmatter block (including the --- delimiters)."""
    lines = [DELIMITER]
    for key, value in data.items():
        if value is None:
            continue
        _emit_value(key, value, 0, lines)
    lines.append(DELIMITER)
    return "\n".join(lines) + "\n"

# ===== steer/skill.py =====

"""
The Skill model: load, inspect, and discover Agent Skills.

A skill is a directory containing a SKILL.md file: YAML frontmatter
(name, description, and optional fields) followed by a markdown body.
This module is the shared representation used by validate, create,
distribute, and the runtime components.
"""


parse_frontmatter = parse

# Fields defined by the open Agent Skills spec (agentskills.io).
SPEC_FIELDS = {"name", "description", "license", "compatibility", "metadata", "allowed-tools"}

# Claude Code frontmatter extensions: valid there, ignored elsewhere.
CLAUDE_CODE_FIELDS = {
    "when_to_use", "argument-hint", "arguments", "disable-model-invocation",
    "user-invocable", "disallowed-tools", "model", "effort", "context",
    "agent", "hooks", "paths", "shell",
}


class SkillNotFound(Exception):
    """Raised when a path does not contain a SKILL.md."""


@dataclass
class Skill:
    """A loaded skill directory."""
    path: Path                          # The skill directory
    frontmatter: Dict[str, Any] = field(default_factory=dict)
    body: str = ""
    problems: List[str] = field(default_factory=list)  # frontmatter parse issues
    has_frontmatter: bool = True

    @property
    def name(self) -> str:
        value = self.frontmatter.get("name", "")
        return value if isinstance(value, str) else str(value)

    @property
    def description(self) -> str:
        value = self.frontmatter.get("description", "")
        return value if isinstance(value, str) else str(value)

    @property
    def dir_name(self) -> str:
        return self.path.name

    @property
    def version(self) -> Optional[str]:
        meta = self.frontmatter.get("metadata")
        if isinstance(meta, dict):
            version = meta.get("version")
            return str(version) if version is not None else None
        return None

    @property
    def skill_md(self) -> Path:
        return self.path / SKILL_FILE

    @classmethod
    def load(cls, path: Union[str, Path]) -> "Skill":
        """Load a skill from a directory (or a direct path to SKILL.md)."""
        p = Path(path).expanduser()
        if p.is_file() and p.name == SKILL_FILE:
            p = p.parent
        skill_md = p / SKILL_FILE
        if not skill_md.is_file():
            raise SkillNotFound(f"No {SKILL_FILE} found in {p}")

        content = skill_md.read_text(encoding="utf-8")
        fm_text, body = split_document(content)
        if fm_text is None:
            return cls(path=p.resolve(), frontmatter={}, body=body,
                       problems=["missing frontmatter block (--- ... ---)"],
                       has_frontmatter=False)
        data, problems = parse_frontmatter(fm_text)
        return cls(path=p.resolve(), frontmatter=data, body=body, problems=problems)

    def files(self) -> List[Path]:
        """All files in the skill directory, junk excluded."""
        results = []
        for f in sorted(self.path.rglob("*")):
            if not f.is_file():
                continue
            parts = f.relative_to(self.path).parts
            if any(part in (".git", "__pycache__", ".steer", ".venv") for part in parts):
                continue
            if f.name == ".DS_Store":
                continue
            results.append(f)
        return results

    def total_size(self) -> int:
        return sum(f.stat().st_size for f in self.files())


def discover(project_dir: str = ".", roots: Optional[List[Path]] = None) -> List[Skill]:
    """Find installed skills across the standard search roots.

    Scans one directory level inside each root. On name collisions the
    earliest root wins (project scope shadows user scope, matching how
    agent products resolve them).
    """
    seen: Dict[str, Skill] = {}
    for root in roots if roots is not None else skill_search_roots(project_dir):
        if not root.is_dir():
            continue
        for child in sorted(root.iterdir()):
            if not child.is_dir() or not (child / SKILL_FILE).is_file():
                continue
            try:
                skill = Skill.load(child)
            except (OSError, SkillNotFound):
                continue
            key = skill.name or skill.dir_name
            if key not in seen:
                seen[key] = skill
    return list(seen.values())

# ===== steer/runtime_cli.py =====

"""
The runtime CLI core: skill resolution, output plumbing, and the
registry the per-component command modules (cli_secrets, cli_store,
cli_learn, cli_context, cli_flow, cli_proc) plug into.

Two entry points share these modules. The installed `steer` CLI imports
all of them (cli.py), and `steer new` copies this core plus exactly the
chosen components' modules into a skill's bundled runtime
(scripts/steer.py, see vendor.py), so installed skills run these
commands without steer on the machine and a subset bundle contains no
code for components it lacks.

VENDORED_SKILL_ROOT is the vendoring seam: None under the installed CLI;
the bundled runtime sets it to the directory of the skill it ships in,
which makes skill, flow, and version resolution positional (the file
knows where it lives) instead of inferred from --skill flags or the
working directory. Hints spell commands via output.CLI_HINT, which the
bundle rebinds the same way.
"""



# Canonical component order: registration, --help, and bundle sections
# all follow it regardless of import order.
COMPONENT_ORDER = ("secrets", "store", "context", "flow", "proc", "learn")

# Vendoring seam (see module docstring).
VENDORED_SKILL_ROOT: Optional[Path] = None

# component name -> its argparse registrar; cli_<component> modules add
# themselves via @runtime_command when imported (or, in a bundle, when
# their amalgamated body runs).
RUNTIME_REGISTRARS: Dict[str, Callable] = {}


def runtime_command(name: str):
    """Register a component's CLI registrar under its component name."""

    def register(fn):
        RUNTIME_REGISTRARS[name] = fn
        return fn

    return register


def _err(message: str) -> int:
    print(f"error: {message}", file=sys.stderr)
    return 1


def _emit(args, message: str, code: int = 0, **data) -> int:
    """One outcome, two audiences: a human line, or JSON with --json."""
    if getattr(args, "json", False):
        payload = {"ok": code == 0, **data, "message": message}
        output_json(payload)
    else:
        print(message)
    return code


def _vendored_skill_name() -> Optional[str]:
    if VENDORED_SKILL_ROOT is None:
        return None
    try:
        skill = Skill.load(VENDORED_SKILL_ROOT)
    except (OSError, SkillNotFound):
        return VENDORED_SKILL_ROOT.name
    return skill.name or VENDORED_SKILL_ROOT.name


def _resolve_skill(args, needed_for: str) -> Optional[str]:
    # A bundle's positional identity outranks STEER_SKILL: the env var
    # disambiguates when steer can't tell which skill is meant, but this
    # file ships inside one; an inherited env var must not redirect its
    # secrets/store/lessons to another skill. Deliberately not
    # infer_skill_name(start=VENDORED_SKILL_ROOT) either: with the
    # bundle's own SKILL.md gone that would walk UP and adopt an
    # enclosing skill's name, while _vendored_skill_name falls back to
    # the directory name and can't cross the skill boundary.
    name = (getattr(args, "skill", None)
            or _vendored_skill_name()
            or os.environ.get(SKILL_ENV)
            or infer_skill_name())
    if not name:
        _err(
            f"Could not determine which skill {needed_for} belongs to. "
            f"Pass --skill <name>, set STEER_SKILL, or run from inside a "
            f"skill directory."
        )
        return None
    return name


def register_runtime_commands(sub, components=None) -> None:
    """Register runtime subcommands; components=None means all registered."""
    for name in COMPONENT_ORDER:
        registrar = RUNTIME_REGISTRARS.get(name)
        if registrar is None:
            continue
        if components is not None and name not in components:
            continue
        registrar(sub)


def runtime_main(argv: Optional[List[str]] = None,
                 components: Optional[List[str]] = None,
                 prog: str = "steer",
                 version: Optional[str] = None) -> int:
    """Entry point for a bundled runtime: only runtime commands, no authoring."""
    included = [c for c in COMPONENT_ORDER
                if c in RUNTIME_REGISTRARS
                and (components is None or c in components)]
    parser = argparse.ArgumentParser(
        prog=prog,
        description=f"Steer runtime bundled with this skill. "
                    f"Components: {', '.join(included)}.",
    )
    if version:
        parser.add_argument("--version", action="version",
                            version=f"{prog} (steer runtime) {version}")
    sub = parser.add_subparsers(dest="command", required=True)
    register_runtime_commands(sub, included)
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except ValueError as exc:
        # Steer raises ValueError for user-fixable input problems
        # (bad skill/flow/process names, bad scopes): print, don't trace.
        return _err(str(exc))
    except KeyboardInterrupt:
        return 130

# ===== steer/context.py =====

"""
Context gathering: one call that answers "where am I, what is this
project, what can I use here?"

Every serious skill starts with a hand-rolled "figure out the situation"
preamble: git probes, marker-file checks, `command -v` ladders,
host-agent detection. Steer turns that into a single snapshot, available
as markdown (for the agent to read) or JSON (for scripts).

Sections: system, agent, git, project, tools, env.

Usage:
    from steer.context import gather, to_markdown
    snapshot = gather()                  # all sections
    print(to_markdown(snapshot))

CLI:
    steer context                # markdown
    steer context --json
    steer context --only git,project
"""


SECTIONS = ("system", "agent", "git", "project", "tools", "env")

# Binaries worth knowing about, probed on PATH.
DEFAULT_TOOLS = [
    "git", "gh", "docker", "node", "npm", "pnpm", "yarn", "bun", "deno",
    "python3", "uv", "pip3", "pipx", "cargo", "go", "make", "cmake",
    "jq", "rg", "curl", "sqlite3", "psql", "kubectl", "terraform",
]

# Environment markers for the agent hosting this process.
_AGENT_MARKERS = [
    ("CLAUDECODE", "claude-code"),
    ("CLAUDE_CODE_ENTRYPOINT", "claude-code"),
    ("CODEX_CI", "openai-codex"),
    ("CODEX_HOME", "openai-codex"),
    ("CURSOR_TRACE_ID", "cursor"),
    ("GEMINI_CLI", "gemini-cli"),
    ("GITHUB_COPILOT_AGENT", "github-copilot"),
    ("AMP_SESSION_ID", "amp"),
    ("GOOSE_SESSION", "goose"),
]

# Project marker files -> what they indicate.
_PROJECT_MARKERS = [
    ("package.json", "node"),
    ("pyproject.toml", "python"),
    ("requirements.txt", "python"),
    ("setup.py", "python"),
    ("Cargo.toml", "rust"),
    ("go.mod", "go"),
    ("Gemfile", "ruby"),
    ("pom.xml", "java-maven"),
    ("build.gradle", "java-gradle"),
    ("build.gradle.kts", "java-gradle"),
    ("mix.exs", "elixir"),
    ("composer.json", "php"),
]

_PACKAGE_MANAGER_LOCKS = [
    ("uv.lock", "uv"),
    ("poetry.lock", "poetry"),
    ("Pipfile.lock", "pipenv"),
    ("package-lock.json", "npm"),
    ("pnpm-lock.yaml", "pnpm"),
    ("yarn.lock", "yarn"),
    ("bun.lockb", "bun"),
    ("bun.lock", "bun"),
]

_EXTRA_MARKERS = [
    ("Dockerfile", "docker"),
    ("docker-compose.yml", "docker-compose"),
    ("docker-compose.yaml", "docker-compose"),
    ("Makefile", "make"),
    (".github/workflows", "github-actions"),
    (".gitlab-ci.yml", "gitlab-ci"),
    ("SKILL.md", "agent-skill"),
]

# Safe-to-report environment variables (never dump the environment).
_ENV_ALLOWLIST = ["CI", "TERM", "LANG", "SHELL", "VIRTUAL_ENV", "NODE_ENV"]

_GIT_TIMEOUT = 5


def _git(args: List[str], cwd: str) -> Optional[str]:
    try:
        proc = subprocess.run(
            ["git", *args], cwd=cwd, capture_output=True, text=True,
            timeout=_GIT_TIMEOUT,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    return proc.stdout.rstrip("\n")


def _gather_system() -> Dict[str, Any]:
    return {
        "os": platform.system(),
        "release": platform.release(),
        "arch": platform.machine(),
        "python": platform.python_version(),
        "cwd": os.getcwd(),
    }


def _gather_agent() -> Dict[str, Any]:
    detected = "unknown"
    for env_var, agent_name in _AGENT_MARKERS:
        if os.environ.get(env_var):
            detected = agent_name
            break
    return {
        "host_agent": detected,
        "is_ci": bool(os.environ.get("CI")),
        "is_tty": sys.stdout.isatty(),
    }


def _gather_git(workspace: str) -> Dict[str, Any]:
    if shutil.which("git") is None:
        return {"available": False}
    inside = _git(["rev-parse", "--is-inside-work-tree"], workspace)
    if inside != "true":
        return {"available": True, "in_repo": False}

    info: Dict[str, Any] = {"available": True, "in_repo": True}
    info["branch"] = _git(["rev-parse", "--abbrev-ref", "HEAD"], workspace)
    status = _git(["status", "--porcelain"], workspace)
    lines = [ln for ln in (status or "").splitlines() if ln.strip()]
    info["dirty_files"] = len(lines)
    info["untracked_files"] = len([ln for ln in lines if ln.startswith("??")])
    log = _git(["log", "--oneline", "-3"], workspace)
    info["recent_commits"] = (log or "").splitlines()
    remotes = _git(["remote"], workspace)
    info["remotes"] = (remotes or "").splitlines()
    git_dir = _git(["rev-parse", "--git-dir"], workspace)
    common_dir = _git(["rev-parse", "--git-common-dir"], workspace)
    info["is_linked_worktree"] = bool(
        git_dir and common_dir and git_dir != common_dir
    )
    return info


def _gather_project(workspace: str) -> Dict[str, Any]:
    root = Path(workspace).expanduser()
    types: List[str] = []
    markers: List[str] = []
    package_managers: List[str] = []

    for marker, kind in _PROJECT_MARKERS:
        if (root / marker).exists():
            markers.append(marker)
            if kind not in types:
                types.append(kind)
    for lock, manager in _PACKAGE_MANAGER_LOCKS:
        if (root / lock).exists() and manager not in package_managers:
            package_managers.append(manager)
    extras = [name for marker, name in _EXTRA_MARKERS if (root / marker).exists()]

    return {
        "types": types,
        "package_managers": package_managers,
        "markers": markers,
        "extras": extras,
    }


def _gather_tools(extra: Optional[Iterable[str]] = None) -> Dict[str, Any]:
    names = list(DEFAULT_TOOLS)
    for name in extra or []:
        if name and name not in names:
            names.append(name)
    available = [name for name in names if shutil.which(name)]
    missing = [name for name in names if name not in available]
    return {"available": available, "missing": missing}


def _gather_env() -> Dict[str, Any]:
    return {name: os.environ[name] for name in _ENV_ALLOWLIST if os.environ.get(name)}


def gather(workspace: str = ".", only: Optional[Iterable[str]] = None,
           tools: Optional[Iterable[str]] = None) -> Dict[str, Any]:
    """Collect a context snapshot.

    Args:
        workspace: Directory to inspect (git/project sections).
        only: Optional subset of SECTIONS to collect.
        tools: Extra binary names to probe in the tools section.
    """
    wanted = list(only) if only else list(SECTIONS)
    unknown = [s for s in wanted if s not in SECTIONS]
    if unknown:
        raise ValueError(f"Unknown context sections: {', '.join(unknown)}")

    snapshot: Dict[str, Any] = {}
    if "system" in wanted:
        snapshot["system"] = _gather_system()
    if "agent" in wanted:
        snapshot["agent"] = _gather_agent()
    if "git" in wanted:
        snapshot["git"] = _gather_git(workspace)
    if "project" in wanted:
        snapshot["project"] = _gather_project(workspace)
    if "tools" in wanted:
        snapshot["tools"] = _gather_tools(tools)
    if "env" in wanted:
        snapshot["env"] = _gather_env()
    return snapshot


def to_markdown(snapshot: Dict[str, Any]) -> str:
    """Render a snapshot as compact markdown for an agent to read."""
    lines: List[str] = ["## Context snapshot"]

    system = snapshot.get("system")
    if system:
        lines.append(
            f"- **System**: {system['os']} {system['arch']}, "
            f"Python {system['python']}, cwd `{system['cwd']}`"
        )
    agent = snapshot.get("agent")
    if agent:
        flags = []
        if agent.get("is_ci"):
            flags.append("CI")
        if not agent.get("is_tty"):
            flags.append("non-interactive")
        suffix = f" ({', '.join(flags)})" if flags else ""
        lines.append(f"- **Host agent**: {agent['host_agent']}{suffix}")

    git = snapshot.get("git")
    if git:
        if not git.get("available"):
            lines.append("- **Git**: not installed")
        elif not git.get("in_repo"):
            lines.append("- **Git**: not a repository")
        else:
            worktree = ", linked worktree" if git.get("is_linked_worktree") else ""
            lines.append(
                f"- **Git**: branch `{git.get('branch')}`, "
                f"{git.get('dirty_files', 0)} dirty files"
                f" ({git.get('untracked_files', 0)} untracked){worktree}"
            )
            for commit in git.get("recent_commits", []):
                lines.append(f"  - `{commit}`")

    project = snapshot.get("project")
    if project:
        types = ", ".join(project["types"]) or "none detected"
        lines.append(f"- **Project**: {types}")
        if project["package_managers"]:
            lines.append(f"  - package managers: {', '.join(project['package_managers'])}")
        if project["extras"]:
            lines.append(f"  - also present: {', '.join(project['extras'])}")

    tools = snapshot.get("tools")
    if tools:
        lines.append(f"- **Tools on PATH**: {', '.join(tools['available'])}")
        if tools["missing"]:
            lines.append(f"  - missing: {', '.join(tools['missing'])}")

    env = snapshot.get("env")
    if env:
        pairs = ", ".join(f"{k}={v}" for k, v in env.items())
        lines.append(f"- **Env**: {pairs}")

    return "\n".join(lines)

# ===== steer/cli_context.py =====

"""The `context` runtime command (see runtime_cli.py for the plumbing)."""



def _cmd_context(args) -> int:
    pass

    only = None
    if args.only:
        only = [s.strip() for s in args.only.split(",") if s.strip()]
    tools = None
    if args.tools:
        tools = [t.strip() for t in args.tools.split(",") if t.strip()]
    try:
        snapshot = gather(workspace=args.workspace, only=only, tools=tools)
    except ValueError as exc:
        return _err(str(exc))
    if args.json:
        output_json(snapshot)
    else:
        print(to_markdown(snapshot))
    return 0


@runtime_command("context")
def register_context_cli(sub) -> None:
    p_ctx = sub.add_parser("context", help="Situational snapshot")
    p_ctx.add_argument("--json", action="store_true")
    p_ctx.add_argument("--only", help="Sections: system,agent,git,project,tools,env")
    p_ctx.add_argument("--tools", help="Extra binaries to probe (comma-separated)")
    p_ctx.add_argument("--workspace", default=".")
    p_ctx.set_defaults(func=_cmd_context)

# ===== steer/proc.py =====

"""
Managed background processes for skills.

Skills that start dev servers or long-running helpers all hand-roll the
same fragile bash: spawn, poll a port, write a PID file, remember to
TERM-then-KILL. Steer owns that lifecycle:

    steer proc start web --ready-port 5173 -- npm run dev
    steer proc status web
    steer proc logs web
    steer proc stop web

Bookkeeping lives in ``<workspace>/.steer/proc/<name>/`` (pid, meta.json,
log). Steer only ever stops processes it started, and treats a recycled
PID (different executable) as stale rather than killable.
"""




class ProcError(Exception):
    """A managed-process operation failed."""


def _proc_dir(name: str, workspace: str, create: bool = False) -> Path:
    pass

    safe = checked_path_component(name, "process")
    path = workspace_steer_dir(workspace, create=create) / "proc" / safe
    if create:
        path.mkdir(parents=True, exist_ok=True)
    return path


def _read_meta(directory: Path) -> Optional[Dict[str, Any]]:
    try:
        return json.loads((directory / "meta.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def _pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True


def _pid_matches(pid: int, expected_exe: str) -> bool:
    """Best-effort guard against recycled PIDs: reject zombies and
    processes whose command clearly differs from what we started.

    Case-insensitive on purpose: macOS framework Python re-execs as
    `.../Python.app/Contents/MacOS/Python` when argv[0] said
    `.../bin/python`.
    """
    try:
        proc = subprocess.run(
            ["ps", "-o", "state=,command=", "-p", str(pid)],
            capture_output=True, text=True, timeout=5,
        )
    except (OSError, subprocess.TimeoutExpired):
        return True  # Can't check; assume it's ours
    output = proc.stdout.strip()
    if not output:
        return False  # ps has no record of the pid
    state, _, command = output.partition(" ")
    if state.startswith("Z"):
        return False  # defunct: still signalable, but not running
    command = command.strip()
    if not command:
        return True  # args unreadable; _pid_alive already vouched for it
    return Path(expected_exe).name.lower() in command.lower()


def _port_open(port: int, host: str = "127.0.0.1") -> bool:
    try:
        with socket.create_connection((host, port), timeout=0.25):
            return True
    except OSError:
        return False


def start(name: str, command: List[str], workspace: str = ".",
          ready_port: Optional[int] = None, ready_log: Optional[str] = None,
          timeout: float = 30.0, cwd: Optional[str] = None,
          env: Optional[Dict[str, str]] = None) -> Dict[str, Any]:
    """Start a managed background process.

    Readiness: waits for `ready_port` to accept connections, or for
    `ready_log` (a substring) to appear in the log, or, with neither,
    just checks the process survives half a second.

    Returns a status dict; raises ProcError on failure (with log tail).
    """
    if not command:
        raise ProcError("No command given")
    existing = status(name, workspace)
    if existing.get("running"):
        raise ProcError(
            f"Process '{name}' is already running (pid {existing['pid']}). "
            f"Stop it first: steer proc stop {name}"
        )

    directory = _proc_dir(name, workspace, create=True)
    log_path = directory / "log"
    run_cwd = str(Path(cwd).expanduser()) if cwd else str(Path(workspace).expanduser())

    full_env = dict(os.environ)
    if env:
        full_env.update(env)

    with open(log_path, "ab") as log_file:
        log_file.write(
            f"\n--- steer proc start {datetime.now(timezone.utc).isoformat()} "
            f"--- {shlex.join(command)}\n".encode()
        )
        try:
            child = subprocess.Popen(
                command, cwd=run_cwd, env=full_env,
                stdout=log_file, stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                start_new_session=True,  # Detach: survive the parent shell
            )
        except OSError as exc:
            raise ProcError(f"Failed to start {command[0]!r}: {exc}") from exc

    meta = {
        "name": name,
        "pid": child.pid,
        "command": command,
        "cwd": run_cwd,
        "started_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "ready_port": ready_port,
        "owner_pid": os.getpid(),
    }
    (directory / "meta.json").write_text(json.dumps(meta, indent=2) + "\n",
                                         encoding="utf-8")

    # Readiness wait
    deadline = time.monotonic() + timeout
    ready = ready_port is None and ready_log is None
    while time.monotonic() < deadline:
        if child.poll() is not None:
            tail = logs(name, workspace, lines=15)
            raise ProcError(
                f"Process '{name}' exited immediately "
                f"(code {child.returncode}). Log tail:\n{tail}"
            )
        if ready_port is not None and _port_open(ready_port):
            ready = True
            break
        if ready_log is not None:
            try:
                if ready_log in log_path.read_text(encoding="utf-8", errors="replace"):
                    ready = True
                    break
            except OSError:
                pass
        if ready_port is None and ready_log is None:
            time.sleep(0.5)
            ready = child.poll() is None
            break
        time.sleep(0.25)

    if not ready:
        stop(name, workspace)
        tail = logs(name, workspace, lines=15)
        raise ProcError(
            f"Process '{name}' did not become ready within {timeout:.0f}s. "
            f"Stopped it. Log tail:\n{tail}"
        )
    return status(name, workspace)


def status(name: str, workspace: str = ".") -> Dict[str, Any]:
    """Status of one managed process."""
    directory = _proc_dir(name, workspace)
    meta = _read_meta(directory)
    if meta is None:
        return {"name": name, "running": False, "known": False}
    pid = int(meta.get("pid", 0))
    running = (
        pid > 0
        and _pid_alive(pid)
        and _pid_matches(pid, meta.get("command", ["?"])[0])
    )
    result = {
        "name": name,
        "known": True,
        "running": running,
        "pid": pid,
        "command": meta.get("command"),
        "started_at": meta.get("started_at"),
        "log": str(directory / "log"),
    }
    if meta.get("ready_port"):
        result["ready_port"] = meta["ready_port"]
        if running:
            result["port_open"] = _port_open(int(meta["ready_port"]))
    return result


def list_procs(workspace: str = ".") -> List[Dict[str, Any]]:
    """Status of every process steer knows about in this workspace."""
    base = workspace_steer_dir(workspace) / "proc"
    if not base.is_dir():
        return []
    return [status(child.name, workspace) for child in sorted(base.iterdir())
            if child.is_dir()]


def logs(name: str, workspace: str = ".", lines: int = 50) -> str:
    """Last N lines of a managed process's log."""
    log_path = _proc_dir(name, workspace) / "log"
    try:
        content = log_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    return "\n".join(content.splitlines()[-lines:])


def stop(name: str, workspace: str = ".", timeout: float = 5.0) -> Dict[str, Any]:
    """Stop a managed process: SIGTERM, wait, then SIGKILL."""
    info = status(name, workspace)
    if not info.get("known"):
        raise ProcError(f"Unknown process: '{name}'")
    if not info.get("running"):
        return {**info, "stopped": False, "reason": "not running"}

    pid = info["pid"]
    try:
        # The process group, so children (npm -> node) die too.
        os.killpg(pid, signal.SIGTERM)
    except (ProcessLookupError, PermissionError, OSError):
        try:
            os.kill(pid, signal.SIGTERM)
        except OSError:
            pass

    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if not _pid_alive(pid):
            return {**status(name, workspace), "stopped": True, "forced": False}
        time.sleep(0.2)

    try:
        os.killpg(pid, signal.SIGKILL)
    except (ProcessLookupError, PermissionError, OSError):
        try:
            os.kill(pid, signal.SIGKILL)
        except OSError:
            pass
    time.sleep(0.2)
    return {**status(name, workspace), "stopped": True, "forced": True}

# ===== steer/cli_proc.py =====

"""The `proc` runtime command (see runtime_cli.py for the plumbing)."""



def _cmd_proc(args) -> int:
    pass

    try:
        if args.proc_cmd == "start":
            command = list(args.command or [])
            if command and command[0] == "--":
                command = command[1:]
            info = start(
                args.name, command, workspace=args.workspace,
                ready_port=args.ready_port, ready_log=args.ready_log,
                timeout=args.timeout, cwd=args.cwd,
            )
            if args.json:
                output_json(info)
            else:
                port = f" (port {info['ready_port']} open)" if info.get("port_open") else ""
                print(f"✓ Started '{args.name}' (pid {info['pid']}){port}")
                print(f"  log: {info['log']}")
                print(f"  stop with: {CLI_HINT} proc stop {args.name}")
            return 0
        if args.proc_cmd == "stop":
            info = stop(args.name, workspace=args.workspace)
            if args.json:
                output_json(info)
            elif info.get("stopped"):
                forced = " (forced)" if info.get("forced") else ""
                print(f"✓ Stopped '{args.name}'{forced}")
            else:
                print(f"'{args.name}' was not running.")
            return 0
        if args.proc_cmd == "status":
            if args.name:
                info = status(args.name, workspace=args.workspace)
                if args.json:
                    output_json(info)
                elif not info.get("known"):
                    print(f"No managed process named '{args.name}'.")
                    return 1
                else:
                    state = "running" if info["running"] else "stopped"
                    print(f"{args.name}: {state} (pid {info.get('pid')}, "
                          f"started {info.get('started_at')})")
                return 0
            infos = list_procs(args.workspace)
            if args.json:
                output_json(infos)
            elif not infos:
                print("No managed processes in this workspace.")
            else:
                for info in infos:
                    state = "running" if info["running"] else "stopped"
                    print(f"{info['name']}: {state} (pid {info.get('pid')})")
            return 0
        if args.proc_cmd == "logs":
            print(logs(args.name, workspace=args.workspace, lines=args.lines))
            return 0
    except ProcError as exc:
        return _err(str(exc))
    return _err(f"Unknown proc command: {args.proc_cmd}")


@runtime_command("proc")
def register_proc_cli(sub) -> None:
    p_proc = sub.add_parser("proc", help="Managed background processes")
    proc_sub = p_proc.add_subparsers(dest="proc_cmd", required=True)
    sp = proc_sub.add_parser("start")
    sp.add_argument("name")
    sp.add_argument("--ready-port", type=int, help="Wait until this port accepts")
    sp.add_argument("--ready-log", help="Wait until this text appears in the log")
    sp.add_argument("--timeout", type=float, default=30.0)
    sp.add_argument("--cwd", help="Working directory for the process")
    sp.add_argument("command", nargs="*",
                    help="The command to run, after a -- separator: "
                         "steer proc start web --ready-port 5173 -- npm run dev")
    for cmd in ("stop", "logs"):
        spc = proc_sub.add_parser(cmd)
        spc.add_argument("name")
        if cmd == "logs":
            spc.add_argument("-n", "--lines", type=int, default=50)
    sps = proc_sub.add_parser("status")
    sps.add_argument("name", nargs="?")
    for spx in (sp, sps, *[proc_sub.choices[c] for c in ("stop", "logs")]):
        spx.add_argument("--workspace", default=".")
        spx.add_argument("--json", action="store_true")
    for spx in proc_sub.choices.values():
        spx.set_defaults(func=_cmd_proc)

# ===== steer/learn.py =====

"""
Learning: skills that improve from their own runs.

Skills are static; agents repeat the same mistakes run after run. The
memory systems that hold up in practice share one shape: automatic capture,
deterministic curation, gated application. Steer implements that loop for
skills:

- **Capture**: the agent records lessons as it works:
  ``steer learn note "Use the EU endpoint for EU accounts" --kind correction``
- **Apply**: at the start of a run the agent reads the bounded digest:
  ``steer learn show``
- **Curate**: deterministic, no LLM inside the framework (the agent IS
  the reflector): exact-duplicate notes bump a confirmation counter,
  ``confirm``/``dispute`` adjust scores, lessons disputed more than
  confirmed auto-archive, and a hard cap evicts the weakest.
- **Promote**: the human-gated path into the shipped skill:
  ``steer learn promote <id>`` appends to the skill's ``learnings.md``.

Where everything lives. Lessons stay OUTSIDE the skill directory (skill
dirs get zipped, uploaded, and upstream-updated; learned data must
survive reinstalls and must never ship by accident):

    ~/.steer/skills/<name>/
    ├── lessons.db       # source of truth (SQLite: lessons + runs)
    └── LEARNINGS.md     # auto-maintained readable mirror of lessons.db
    <skill-dir>/learnings.md   # promoted lessons only; ships with the skill

Auto-learning: ``steer learn reflect`` is a Claude Code Stop hook. It
deterministically scans the session transcript for correction/failure
signals and, once, blocks the stop with instructions telling the agent
to distill lessons before finishing. ``steer new --auto-learn`` wires it
into a skill's frontmatter ``hooks`` so capture no longer depends on the
agent remembering.
"""



KINDS = ("correction", "failure", "success", "preference", "workaround", "note")

ACTIVE = "active"
PINNED = "pinned"
ARCHIVED = "archived"
PROMOTED = "promoted"

MAX_LESSON_CHARS = 500       # lessons are atomic rules, not essays
MAX_ACTIVE_LESSONS = 200     # hard cap; weakest evicted past this
DEFAULT_SHOW_BUDGET = 2000   # chars in the `show` digest (~500 tokens)

LEARNINGS_FILE = "learnings.md"   # promoted lessons, inside the skill (ships)
MIRROR_FILE = "LEARNINGS.md"      # auto-maintained readable mirror, ~/.steer

# Obvious credential shapes. Lessons are plain text that may eventually be
# promoted into a shipped file. Refuse anything that smells like a secret.
_SECRET_PATTERNS = [
    re.compile(r"(?i)(api[_-]?key|secret|token|passwd|password|bearer)\s*[:=]\s*\S+"),
    re.compile(r"\bsk-[A-Za-z0-9_-]{8,}"),
    re.compile(r"\bghp_[A-Za-z0-9]{20,}"),
    re.compile(r"\bAKIA[0-9A-Z]{12,}"),
    re.compile(r"\bxox[bpars]-[A-Za-z0-9-]+"),
]


class LessonRejected(Exception):
    """A lesson was refused (too long, or credential-shaped)."""


def _now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def _normalize(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip().rstrip(".").lower()


class Learnings:
    """The learning loop for one skill."""

    def __init__(self, skill: str, path: Optional[Path] = None):
        if not skill and path is None:
            raise ValueError("Learnings requires a skill name")
        self.skill = skill
        self.path = path or (skill_data_dir(skill, create=True) / "lessons.db")
        self._conn: Optional[sqlite3.Connection] = None

    @property
    def conn(self) -> sqlite3.Connection:
        if self._conn is None:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            self._conn = sqlite3.connect(self.path)
            self._conn.row_factory = sqlite3.Row
            self._conn.execute("PRAGMA journal_mode=WAL")
            self._conn.execute(
                "CREATE TABLE IF NOT EXISTS lessons ("
                "  id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "  text TEXT NOT NULL,"
                "  normalized TEXT NOT NULL,"
                "  kind TEXT NOT NULL,"
                "  context TEXT,"
                "  evidence TEXT,"
                "  skill_version TEXT,"
                "  workspace TEXT,"
                "  status TEXT NOT NULL DEFAULT 'active',"
                "  confirmations INTEGER NOT NULL DEFAULT 1,"
                "  contradictions INTEGER NOT NULL DEFAULT 0,"
                "  created_at TEXT NOT NULL,"
                "  last_seen_at TEXT NOT NULL"
                ")"
            )
            self._conn.execute(
                "CREATE TABLE IF NOT EXISTS runs ("
                "  id INTEGER PRIMARY KEY AUTOINCREMENT,"
                "  status TEXT NOT NULL,"
                "  note TEXT,"
                "  workspace TEXT,"
                "  skill_version TEXT,"
                "  created_at TEXT NOT NULL"
                ")"
            )
        return self._conn

    def close(self) -> None:
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    def __enter__(self) -> "Learnings":
        return self

    def __exit__(self, *exc) -> None:
        self.close()

    # -- capture --------------------------------------------------------

    def note(self, text: str, kind: str = "note", context: Optional[str] = None,
             evidence: Optional[str] = None, skill_version: Optional[str] = None,
             workspace: Optional[str] = None) -> Dict[str, Any]:
        """Record a lesson. Exact duplicates confirm instead of duplicating.

        Returns {"id", "action"} where action is "added" or "confirmed".
        """
        text = text.strip()
        if not text:
            raise LessonRejected("Empty lesson.")
        if len(text) > MAX_LESSON_CHARS:
            raise LessonRejected(
                f"Lesson is {len(text)} chars (max {MAX_LESSON_CHARS}). "
                f"Keep lessons atomic: one rule per note; split this one."
            )
        for pattern in _SECRET_PATTERNS:
            if any(pattern.search(part) for part in (text, context, evidence)
                   if part):
                raise LessonRejected(
                    "This looks like it contains a credential. Lessons are "
                    "plain text and can be promoted into shipped files. "
                    "Store secrets with `steer secrets` instead."
                )
        if kind not in KINDS:
            raise LessonRejected(
                f"Unknown kind {kind!r} (use one of: {', '.join(KINDS)})"
            )

        normalized = _normalize(text)
        existing = self.conn.execute(
            "SELECT id FROM lessons WHERE normalized = ? "
            "AND status IN ('active', 'pinned')",
            (normalized,),
        ).fetchone()
        if existing:
            self.confirm(existing["id"])
            return {"id": existing["id"], "action": "confirmed"}

        cur = self.conn.execute(
            "INSERT INTO lessons (text, normalized, kind, context, evidence,"
            " skill_version, workspace, status, created_at, last_seen_at)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, 'active', ?, ?)",
            (text, normalized, kind, context, evidence, skill_version,
             workspace, _now(), _now()),
        )
        self.conn.commit()
        self._evict_past_cap()
        self.sync_mirror()
        return {"id": int(cur.lastrowid), "action": "added"}

    def record_run(self, status: str, note: Optional[str] = None,
                   skill_version: Optional[str] = None,
                   workspace: Optional[str] = None) -> int:
        """Record a run outcome ("ok" or "failed") for stats."""
        if status not in ("ok", "failed"):
            raise ValueError("Run status must be 'ok' or 'failed'")
        cur = self.conn.execute(
            "INSERT INTO runs (status, note, workspace, skill_version,"
            " created_at) VALUES (?, ?, ?, ?, ?)",
            (status, note, workspace, skill_version, _now()),
        )
        self.conn.commit()
        self.sync_mirror()
        return int(cur.lastrowid)

    # -- curation (deterministic: no LLM in the framework) ---------------

    def _get(self, lesson_id: int) -> sqlite3.Row:
        row = self.conn.execute(
            "SELECT * FROM lessons WHERE id = ?", (lesson_id,)
        ).fetchone()
        if row is None:
            raise KeyError(f"No lesson with id {lesson_id}")
        return row

    def confirm(self, lesson_id: int) -> Dict[str, Any]:
        """This lesson helped. Strengthen it."""
        self._get(lesson_id)
        self.conn.execute(
            "UPDATE lessons SET confirmations = confirmations + 1,"
            " last_seen_at = ?,"
            " status = CASE WHEN status = 'archived' THEN 'active'"
            "               ELSE status END"
            " WHERE id = ?",
            (_now(), lesson_id),
        )
        self.conn.commit()
        self.sync_mirror()
        return self.get(lesson_id)

    def dispute(self, lesson_id: int) -> Dict[str, Any]:
        """This lesson was wrong or no longer applies. Weaken it.

        A lesson disputed more than confirmed auto-archives: bounded blast
        radius for bad lessons, reversible by a later confirm.
        """
        self._get(lesson_id)
        self.conn.execute(
            "UPDATE lessons SET contradictions = contradictions + 1,"
            " last_seen_at = ? WHERE id = ?",
            (_now(), lesson_id),
        )
        self.conn.execute(
            "UPDATE lessons SET status = 'archived'"
            " WHERE id = ? AND contradictions > confirmations"
            " AND status IN ('active', 'pinned')",
            (lesson_id,),
        )
        self.conn.commit()
        self.sync_mirror()
        return self.get(lesson_id)

    def pin(self, lesson_id: int) -> None:
        """Pin a lesson: always shown first, never auto-evicted."""
        self._get(lesson_id)
        self.conn.execute(
            "UPDATE lessons SET status = 'pinned', last_seen_at = ?"
            " WHERE id = ?", (_now(), lesson_id),
        )
        self.conn.commit()
        self.sync_mirror()

    def forget(self, lesson_id: int) -> None:
        """Archive a lesson (soft delete; review --all still shows it)."""
        self._get(lesson_id)
        self.conn.execute(
            "UPDATE lessons SET status = 'archived' WHERE id = ?",
            (lesson_id,),
        )
        self.conn.commit()
        self.sync_mirror()

    def _evict_past_cap(self) -> None:
        rows = self.conn.execute(
            "SELECT id FROM lessons WHERE status = 'active'"
            " ORDER BY (confirmations - contradictions) DESC, last_seen_at DESC"
        ).fetchall()
        for row in rows[MAX_ACTIVE_LESSONS:]:
            self.conn.execute(
                "UPDATE lessons SET status = 'archived' WHERE id = ?",
                (row["id"],),
            )
        if len(rows) > MAX_ACTIVE_LESSONS:
            self.conn.commit()

    # -- reading ----------------------------------------------------------

    def get(self, lesson_id: int) -> Dict[str, Any]:
        return dict(self._get(lesson_id))

    def lessons(self, statuses: Optional[List[str]] = None) -> List[Dict[str, Any]]:
        """Lessons ranked: pinned first, then score, then recency."""
        wanted = statuses or [PINNED, ACTIVE]
        marks = ",".join("?" for _ in wanted)
        rows = self.conn.execute(
            f"SELECT * FROM lessons WHERE status IN ({marks})"
            " ORDER BY CASE status WHEN 'pinned' THEN 0 ELSE 1 END,"
            " (confirmations - contradictions) DESC, last_seen_at DESC",
            wanted,
        ).fetchall()
        return [dict(r) for r in rows]

    def digest(self, budget: int = DEFAULT_SHOW_BUDGET,
               current_version: Optional[str] = None) -> str:
        """The bounded markdown the agent reads at the start of a run."""
        ranked = self.lessons()
        if not ranked:
            return (f"(no lessons recorded for this skill yet; capture them "
                    f"as you work: {CLI_HINT} learn note \"...\")")

        lines = [f"## Lessons from previous runs ({self.skill})"]
        shown = 0
        used = len(lines[0])
        for lesson in ranked:
            marker = "★ " if lesson["status"] == PINNED else ""
            stale = ""
            if (current_version and lesson["skill_version"]
                    and lesson["skill_version"] != current_version):
                stale = f" [from v{lesson['skill_version']}]"
            entry = f"- [{lesson['id']}] {marker}{lesson['text']}{stale}"
            if lesson["context"]:
                entry += f" (when: {lesson['context']})"
            if used + len(entry) > budget:
                break
            lines.append(entry)
            used += len(entry)
            shown += 1
        remaining = len(ranked) - shown
        if remaining > 0:
            lines.append(f"- …and {remaining} more: {CLI_HINT} learn review")
        lines.append(
            f"(helped? {CLI_HINT} learn confirm <id> · "
            f"wrong? {CLI_HINT} learn dispute <id>)"
        )
        return "\n".join(lines)

    def stats(self) -> Dict[str, Any]:
        by_status: Dict[str, int] = {}
        for row in self.conn.execute(
            "SELECT status, COUNT(*) AS n FROM lessons GROUP BY status"
        ):
            by_status[row["status"]] = row["n"]
        runs = {"total": 0, "ok": 0, "failed": 0}
        for row in self.conn.execute(
            "SELECT status, COUNT(*) AS n FROM runs GROUP BY status"
        ):
            runs[row["status"]] = row["n"]
            runs["total"] += row["n"]
        last_run = self.conn.execute(
            "SELECT created_at FROM runs ORDER BY id DESC LIMIT 1"
        ).fetchone()
        return {
            "skill": self.skill,
            "lessons": by_status,
            "runs": runs,
            "success_rate": (runs["ok"] / runs["total"]) if runs["total"] else None,
            "last_run": last_run["created_at"] if last_run else None,
        }

    # -- the readable mirror (the "specific place" lessons live) ----------

    def mirror_path(self) -> Path:
        return self.path.parent / MIRROR_FILE

    def sync_mirror(self) -> Path:
        """Regenerate the human/agent-readable LEARNINGS.md next to the DB.

        The DB is the source of truth; the mirror is rewritten after every
        mutation so it can simply be read (or grepped) without the CLI.
        """
        stats = self.stats()
        runs = stats["runs"]
        rate = (f"{stats['success_rate'] * 100:.0f}% ok"
                if stats["success_rate"] is not None else "no runs yet")
        counts = stats["lessons"]
        lines = [
            f"# Learnings: {self.skill}",
            "",
            "<!-- auto-generated by steer learn; source of truth is "
            "lessons.db in this directory. Edit via `steer learn` commands, "
            "not by hand. -->",
            "",
            f"Updated: {_now()} · runs: {runs['total']} ({rate}) · "
            + " · ".join(f"{counts.get(s, 0)} {s}"
                         for s in (PINNED, ACTIVE, PROMOTED, ARCHIVED)),
        ]
        sections = [
            ("Pinned", [PINNED], None),
            ("Active", [ACTIVE], None),
            ("Promoted (shipped in the skill's learnings.md)", [PROMOTED], 10),
            ("Recently archived", [ARCHIVED], 10),
        ]
        for title, statuses, limit in sections:
            entries = self.lessons(statuses)
            if not entries:
                continue
            lines += ["", f"## {title}", ""]
            for lesson in entries[:limit] if limit else entries:
                score = lesson["confirmations"] - lesson["contradictions"]
                line = (f"- [{lesson['id']}] {lesson['text']} "
                        f"({lesson['kind']}, {score:+d}")
                if lesson["context"]:
                    line += f", when: {lesson['context']}"
                line += f", last: {lesson['last_seen_at'][:10]})"
                if lesson["evidence"]:
                    line += f"; evidence: {lesson['evidence']}"
                lines.append(line)
            if limit and len(entries) > limit:
                lines.append(f"- …and {len(entries) - limit} more "
                             f"({CLI_HINT} learn review --all)")
        self.mirror_path().write_text("\n".join(lines) + "\n", encoding="utf-8")
        return self.mirror_path()

    # -- promotion (the human-gated path into the shipped skill) ----------

    def promote(self, lesson_id: int, skill_dir) -> Path:
        """Append a lesson to the skill's learnings.md and mark it promoted.

        This is the author action that turns a learned-locally lesson into
        shipped skill content. The file is plain markdown with provenance
        comments, so diffs are reviewable and upstream merges are sane.
        """
        lesson = self._get(lesson_id)
        target_dir = Path(skill_dir).expanduser()
        if not (target_dir / "SKILL.md").is_file():
            raise FileNotFoundError(
                f"{target_dir} is not a skill directory (no SKILL.md)"
            )
        learnings_path = target_dir / LEARNINGS_FILE
        if not learnings_path.exists():
            learnings_path.write_text(
                "# Learnings\n\n"
                "Lessons promoted from real runs (managed with `steer learn`).\n"
                "Read this before relying on the main instructions.\n\n",
                encoding="utf-8",
            )
        date = _now().split("T")[0]
        entry = f"- {lesson['text']}"
        if lesson["context"]:
            entry += f" (when: {lesson['context']})"
        entry += f" <!-- steer:lesson {lesson['id']} {date} -->\n"
        with open(learnings_path, "a", encoding="utf-8") as f:
            f.write(entry)
        self.conn.execute(
            "UPDATE lessons SET status = 'promoted', last_seen_at = ?"
            " WHERE id = ?", (_now(), lesson_id),
        )
        self.conn.commit()
        self.sync_mirror()
        return learnings_path


# -- auto-learning: the Stop-hook reflection engine -----------------------
#
# `steer learn reflect` runs as a (Claude Code) Stop hook. Steer stays
# LLM-free: it only DETECTS that something worth learning happened
# (user corrections, failed tool calls) and, once per session, blocks the
# stop with instructions telling the agent (the actual reflector) to
# distill lessons and record the run outcome before finishing.

# User-message shapes that signal a correction. Deterministic and
# deliberately conservative: false negatives are cheap (the instruction-
# driven loop still applies), false positives nag.
_CORRECTION_PATTERNS = [
    re.compile(r"^\s*(no|nope|wrong|incorrect|not that|stop)\b[\s,.!]", re.I),
    re.compile(r"\b(that'?s (wrong|not right|not what)|you should have"
               r"|i meant|i didn'?t ask|don'?t do that|undo that"
               r"|use .{1,40} instead|not .{1,40}, use)\b", re.I),
]

# A capture command the agent actually RAN: matched only inside tool-use
# inputs, because a learn-component SKILL.md quotes these commands
# verbatim as instructions and enters the transcript when the skill
# loads. Covers the installed spelling ("steer learn note") and a
# bundled runtime ("... scripts/steer.py learn note") alike.
_CAPTURE_RE = re.compile(r"steer(\.py)?[\"']?\s+learn\s+(note|run)\b")


def _iter_tool_use_inputs(line_obj: Any):
    """Yield the JSON-encoded input of each tool_use block in a line."""
    if not isinstance(line_obj, dict):
        return
    message = (line_obj.get("message")
               if isinstance(line_obj.get("message"), dict) else line_obj)
    content = message.get("content")
    if not isinstance(content, list):
        return
    for part in content:
        if isinstance(part, dict) and part.get("type") == "tool_use":
            yield json.dumps(part.get("input", {}))


def _iter_transcript_text(line_obj: Any):
    """Yield (role, text) pairs from one parsed transcript line.

    Claude Code transcripts are JSONL but the exact line shape varies
    (top-level role/content, or nested under "message"). Walk both.
    """
    if not isinstance(line_obj, dict):
        return
    message = line_obj.get("message") if isinstance(line_obj.get("message"), dict) else line_obj
    role = message.get("role") or line_obj.get("type") or ""
    content = message.get("content")
    if isinstance(content, str):
        yield role, content
    elif isinstance(content, list):
        for part in content:
            if isinstance(part, dict):
                text = part.get("text") or part.get("content")
                if isinstance(text, str):
                    yield role, text


def scan_transcript(path) -> Dict[str, Any]:
    """Deterministically scan a session transcript for learning signals.

    Returns {"corrections": int, "failures": int, "captured": bool,
    "readable": bool}. `captured` means the agent already ran
    `steer learn note`/`run` this session.
    """
    result = {"corrections": 0, "failures": 0, "captured": False,
              "readable": False}
    try:
        raw = Path(path).expanduser().read_text(encoding="utf-8",
                                                errors="replace")
    except OSError:
        return result
    result["readable"] = True

    for line in raw.splitlines():
        line = line.strip()
        if not line:
            continue
        # Cheap signal that doesn't need full parsing
        if '"is_error": true' in line or '"is_error":true' in line:
            result["failures"] += 1
        try:
            obj = json.loads(line)
        except ValueError:
            continue
        for tool_input in _iter_tool_use_inputs(obj):
            if _CAPTURE_RE.search(tool_input):
                result["captured"] = True
        for role, text in _iter_transcript_text(obj):
            if role != "user":
                continue
            if any(p.search(text) for p in _CORRECTION_PATTERNS):
                result["corrections"] += 1
    return result


def reflect(hook_input: Dict[str, Any], skill: str,
            min_signals: int = 1) -> Optional[Dict[str, Any]]:
    """Decide whether to block a stop and ask the agent to distill lessons.

    Returns the Stop-hook decision object ({"decision": "block", ...}) or
    None to allow the stop. Never blocks twice (honors stop_hook_active),
    never blocks when the agent already captured this session.
    """
    if hook_input.get("stop_hook_active"):
        return None
    transcript_path = hook_input.get("transcript_path")
    if not transcript_path:
        return None
    signals = scan_transcript(transcript_path)
    if not signals["readable"] or signals["captured"]:
        return None
    total = signals["corrections"] + signals["failures"]
    if total < min_signals:
        return None

    observed = []
    if signals["corrections"]:
        observed.append(f"{signals['corrections']} user correction(s)")
    if signals["failures"]:
        observed.append(f"{signals['failures']} failed tool call(s)")
    reason = (
        f"steer learn (skill '{skill}'): this session had "
        f"{' and '.join(observed)}, and no lessons were recorded. "
        f"Before finishing:\n"
        f"1. For each durable, reusable lesson run: {CLI_HINT} learn note "
        f"\"<one imperative rule>\" --kind correction --skill {skill} "
        f"(skip one-off trivia; never include secrets)\n"
        f"2. Record the outcome: {CLI_HINT} learn run ok --skill {skill} "
        f"(or 'failed')\n"
        f"Then finish. If nothing is durable, just record the run outcome."
    )
    return {
        "decision": "block",
        "reason": reason,
        "hookSpecificOutput": {
            "hookEventName": "Stop",
            "additionalContext": reason,
        },
    }

# ===== steer/cli_learn.py =====

"""The `learn` runtime command (see runtime_cli.py for the plumbing)."""




def _skill_dir_and_version(skill_name: str):
    """Locate the skill's directory and current version, if findable."""
    candidates = []
    if VENDORED_SKILL_ROOT is not None:
        candidates.append(VENDORED_SKILL_ROOT)
    root = find_skill_root(".")
    if root is not None:
        candidates.append(root)
    for candidate in candidates:
        try:
            skill = Skill.load(candidate)
            if (skill.name or candidate.name) == skill_name:
                return candidate, skill.version
        except SkillNotFound:
            pass
    for skill in discover():
        if (skill.name or skill.dir_name) == skill_name:
            return skill.path, skill.version
    return None, None


def _cmd_learn(args) -> int:
    pass

    skill = _resolve_skill(args, "this lesson")
    if skill is None:
        return 1

    if args.learn_cmd == "reflect":
        # Stop-hook mode: hook JSON on stdin; print a decision (or nothing).
        # Always exit 0: a broken hook must never break the agent.
        try:
            if args.transcript:
                hook_input = {"transcript_path": args.transcript,
                              "stop_hook_active": False}
            else:
                hook_input = json.loads(sys.stdin.read() or "{}")
            if args.scan_only:
                output_json(scan_transcript(
                    hook_input.get("transcript_path", "")))
                return 0
            decision = reflect(hook_input, skill,
                               min_signals=args.min_signals)
            if decision is not None:
                output_json(decision)
        except Exception as exc:  # never block the host agent on a bug
            print(f"steer learn reflect: {exc}", file=sys.stderr)
        return 0

    skill_dir, version = _skill_dir_and_version(skill)

    with Learnings(skill) as learnings:
        try:
            if args.learn_cmd == "note":
                result = learnings.note(
                    args.text, kind=args.kind, context=args.context,
                    evidence=args.evidence, skill_version=version,
                    workspace=str(Path.cwd()),
                )
                verb = ("✓ Lesson recorded" if result["action"] == "added"
                        else "✓ Already known; confirmation strengthened")
                return _emit(args, f"{verb} (id {result['id']})",
                             id=result["id"], action=result["action"])

            if args.learn_cmd == "show":
                digest = learnings.digest(budget=args.budget,
                                          current_version=version)
                if args.json:
                    output_json({"skill": skill, "digest": digest})
                else:
                    print(digest)
                return 0

            if args.learn_cmd in ("confirm", "dispute"):
                action = (learnings.confirm if args.learn_cmd == "confirm"
                          else learnings.dispute)
                lesson = action(args.id)
                score = lesson["confirmations"] - lesson["contradictions"]
                state = (f"score {score:+d}"
                         if lesson["status"] != "archived"
                         else "auto-archived (disputed more than confirmed)")
                return _emit(args, f"✓ Lesson {args.id}: {state}",
                             id=args.id, status=lesson["status"], score=score)

            if args.learn_cmd == "pin":
                learnings.pin(args.id)
                return _emit(args, f"✓ Lesson {args.id} pinned (always shown first).",
                             id=args.id)

            if args.learn_cmd == "forget":
                learnings.forget(args.id)
                return _emit(args, f"✓ Lesson {args.id} archived.", id=args.id)

            if args.learn_cmd == "review":
                statuses = (["pinned", "active", "archived", "promoted"]
                            if args.all else None)
                rows = learnings.lessons(statuses)
                if args.json:
                    output_json(rows)
                    return 0
                if not rows:
                    print(f"No lessons for skill '{skill}' yet.")
                    return 0
                for lesson in rows:
                    score = lesson["confirmations"] - lesson["contradictions"]
                    flags = lesson["status"] if lesson["status"] != "active" else ""
                    print(f"[{lesson['id']:>4}] {score:+d} {lesson['kind']:<10}"
                          f" {flags:<9} {lesson['text']}")
                    if lesson["context"]:
                        print(f"{'':>6} when: {lesson['context']}")
                print(f"\nPromote the keepers into the skill: "
                      f"{CLI_HINT} learn promote <id>")
                return 0

            if args.learn_cmd == "promote":
                target = Path(args.dir).expanduser() if args.dir else skill_dir
                if target is None:
                    return _err(
                        f"Can't find the skill directory for '{skill}'. "
                        f"Pass it explicitly: {CLI_HINT} learn promote "
                        f"{args.id} --dir <skill-dir>"
                    )
                path = learnings.promote(args.id, target)
                if args.json:
                    output_json({"ok": True, "id": args.id, "path": str(path)})
                    return 0
                print(f"✓ Promoted lesson {args.id} into {path}")
                print("  Make sure SKILL.md tells the agent to read "
                      "`learnings.md` before relying on the main instructions, "
                      "then commit/re-package the skill.")
                return 0

            if args.learn_cmd == "run":
                learnings.record_run(args.status, note=args.note,
                                     skill_version=version,
                                     workspace=str(Path.cwd()))
                return _emit(args, f"✓ Run recorded ({args.status}).",
                             status=args.status)

            if args.learn_cmd == "stats":
                stats = learnings.stats()
                if args.json:
                    output_json(stats)
                    return 0
                runs = stats["runs"]
                rate = (f"{stats['success_rate'] * 100:.0f}%"
                        if stats["success_rate"] is not None else "n/a")
                print(f"{skill}: {runs['total']} runs recorded "
                      f"({runs['ok']} ok, {runs['failed']} failed, "
                      f"success {rate})")
                lessons = stats["lessons"]
                parts = [f"{n} {status}" for status, n in sorted(lessons.items())]
                print(f"lessons: {', '.join(parts) if parts else 'none'}")
                if stats["last_run"]:
                    print(f"last run: {stats['last_run']}")
                return 0

        except LessonRejected as exc:
            return _err(str(exc))
        except Exception as exc:  # corrupt lessons.db etc.; match store's UX
            return _err(f"learn: {exc}")
    return _err(f"Unknown learn command: {args.learn_cmd}")


@runtime_command("learn")
def register_learn_cli(sub) -> None:
    p_learn = sub.add_parser("learn",
                             help="Lessons a skill accumulates from its runs")
    learn_sub = p_learn.add_subparsers(dest="learn_cmd", required=True)
    lp = learn_sub.add_parser("note", help="Record a lesson")
    lp.add_argument("text", help="The lesson: one imperative rule, no secrets")
    lp.add_argument("--kind", default="note",
                    choices=("correction", "failure", "success",
                             "preference", "note"))
    lp.add_argument("--context", help="When this applies (trigger condition)")
    lp.add_argument("--evidence", help="Provenance: file, command, or error")
    lp = learn_sub.add_parser("show",
                              help="Bounded digest to read at run start")
    lp.add_argument("--budget", type=int, default=2000,
                    help="Max characters (default 2000)")
    for cmd, help_text in (("confirm", "This lesson helped"),
                           ("dispute", "This lesson was wrong"),
                           ("pin", "Always show first"),
                           ("forget", "Archive a lesson")):
        lp = learn_sub.add_parser(cmd, help=help_text)
        lp.add_argument("id", type=int)
    lp = learn_sub.add_parser("review", help="List lessons with scores")
    lp.add_argument("--all", action="store_true",
                    help="Include archived and promoted lessons")
    lp = learn_sub.add_parser("promote",
                              help="Graduate a lesson into the skill's "
                                   "learnings.md")
    lp.add_argument("id", type=int)
    lp.add_argument("--dir", help="Skill directory (default: resolved)")
    lp = learn_sub.add_parser("run", help="Record a run outcome")
    lp.add_argument("status", choices=("ok", "failed"))
    lp.add_argument("--note", help="What happened")
    learn_sub.add_parser("stats", help="Run counts and lesson totals")
    lp = learn_sub.add_parser(
        "reflect",
        help="Stop-hook auto-learning: scan the session transcript for "
             "corrections/failures and prompt the agent to distill lessons")
    lp.add_argument("--transcript", help="Transcript path (default: from "
                                         "hook JSON on stdin)")
    lp.add_argument("--min-signals", type=int, default=1,
                    help="Signals required before prompting (default 1)")
    lp.add_argument("--scan-only", action="store_true",
                    help="Print the signal scan and exit")
    for lpx in learn_sub.choices.values():
        lpx.add_argument("--skill", help="Skill name (default: inferred)")
        lpx.add_argument("--json", action="store_true")
        lpx.set_defaults(func=_cmd_learn)

# ===== entry point =====

# The bundle knows which skill it belongs to: the one it ships inside.
# Hints spell this file by absolute path so they run from any directory
# (the agent's working directory is usually the workspace, not the skill).
VENDORED_SKILL_ROOT = Path(__file__).resolve().parent.parent
CLI_HINT = "python3 " + shlex.quote(str(Path(__file__).resolve()))

# Sibling scripts import this file as `steer`; alias the module paths the
# package would provide so `from steer.output import ...` keeps working.
_self = sys.modules.get(__name__)
if _self is not None:
    sys.modules.setdefault("steer", _self)
    for _submodule in ('paths', 'output', 'frontmatter', 'skill', 'runtime_cli', 'context', 'cli_context', 'proc', 'cli_proc', 'learn', 'cli_learn'):
        sys.modules.setdefault(f"steer.{_submodule}", _self)

if __name__ == "__main__":
    sys.exit(runtime_main(
        components=list(STEER_RUNTIME_COMPONENTS),
        prog="python3 scripts/steer.py",
        version=__version__,
    ))
